version: '3'
services:
  postgres:
    image: 'postgres:latest'
    ports:
      - "5432:5432" #To access the db locally
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
    depends_on:
      - "api"
      - "web"
  api:
    ports:
      - '5000'
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - PORT=5000
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    depends_on:
      - "postgres"
  web:
    ports:
      - '3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app